import { CompanyDataType } from '@/types/TransactionHistoryTable';

const companies: CompanyDataType[] = [
  {
    key: 1,
    companyName: 'E-Mart',
    address: 'Pkr',
    email: 'example@gmail.com',
    pan: 467234,
    mobile: 9575453423,
    contactPerson: 'abc',
    transactions: [],
  },
  {
    key: 2,
    companyName: 'Test Acc',
    address: 'Pkr',
    email: 'example@gmail.com',
    pan: 467234,
    mobile: 9575453423,
    contactPerson: 'abc',
    transactions: [],
  },
  {
    key: 1,
    companyName: 'Test Nipuna Stores',
    address: 'Pkr',
    email: 'example@gmail.com',
    pan: 467234,
    mobile: 9575453423,
    contactPerson: 'abc',
    transactions: [
      {
        key: 1,
        clientPan: 89573,
        orderDate: 'May 27, 2024 1:40 PM',
        status: 'paid',
        total: 345,
        transactionDetails: [
          {
            key: 1,
            image: '/nipuna-logo.png',
            itemName: 'biscuit',
            price: 20,
            qty: 1,
            unitType: 'piece',
          },
          {
            key: 2,
            image: '/nipuna-logo.png',
            itemName: 'biscuit',
            price: 20,
            qty: 1,
            unitType: 'piece',
          },
          {
            key: 3,
            image: '/nipuna-logo.png',
            itemName: 'biscuit',
            price: 20,
            qty: 1,
            unitType: 'piece',
          },
          {
            key: 4,
            image: '/nipuna-logo.png',
            itemName: 'biscuit',
            price: 20,
            qty: 1,
            unitType: 'piece',
          },
        ],
      },
      {
        key: 2,
        clientPan: 89573,
        orderDate: 'May 27, 2024 1:40 PM',
        status: 'paid',
        total: 345,
        transactionDetails: [
          {
            key: 1,
            image: '/nipuna-logo.png',
            itemName: 'biscuit',
            price: 20,
            qty: 1,
            unitType: 'piece',
          },
          {
            key: 2,
            image: '/nipuna-logo.png',
            itemName: 'biscuit',
            price: 20,
            qty: 1,
            unitType: 'piece',
          },
          {
            key: 3,
            image: '/nipuna-logo.png',
            itemName: 'biscuit',
            price: 20,
            qty: 1,
            unitType: 'piece',
          },
          {
            key: 4,
            image: '/nipuna-logo.png',
            itemName: 'biscuit',
            price: 20,
            qty: 1,
            unitType: 'piece',
          },
        ],
      },
    ],
  },
];

export default companies;
